version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - '5000:5000'
    volumes:
      - ./backend:/app
    env_file: .env
    depends_on:
      - postgres

  postgres:
    image: postgres:14
    environment:
      POSTGRES_DB: audit_logs
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
